### ISSUE TITLE
CST (UTC + 8) seems wrong

### ISSUE THREAD

**Issue by shinya7y** [BMVC2020/BMVC2020.github.io#1]
Hi,

Thank you for organising the conference.

https://github.com/BMVC2020/BMVC2020.github.io/blob/master/programme/schedule.md
```
                 	{{ session.start-time | plus: 6 | append: ":" | append: start-mins | date: "%H:%M" }} - 
                     {{ session.end-time   | plus: 6 | append: ":" | append: end-mins | date: "%H:%M" }}</td>
```
Are `plus: 6` typos for `plus: 7`?

**Comment by ndfcampbell** [comment]
Hi @shinya7y - thanks, you are quite right! All fixed now.
